---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-5cef6ba9bc7fb3a04d0fe1baed1019db
  name: wego-test-app-qzyws6ao
  namespace: wego-system
spec:
  branch: main
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/my-test-org-23/wego-test-app-qzyws6ao.git
