---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-test-app-qzyws6ao
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/my-test-org-23/wego-test-app-qzyws6ao.git

